language: objective-c
osx_image: xcode8
xcode_project: "Test/Thread.xcodeproj"
xcode_scheme: ThreadOSX
xcode_sdk: iphonesimulator10.0
before_install:
  - gem install xcpretty
script:
  - set -o pipefail
  - xcodebuild -project $TRAVIS_XCODE_PROJECT -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK -destination 'name=iPhone 6' test | xcpretty -c